# week05/k8s/frontend.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-w10
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: frontend-container
        image: sit722w10acr.azurecr.io/frontend:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: PRODUCT_API_BASE_URL
          value: http://product-service-w10:8000
        - name: ORDER_API_BASE_URL
          value: http://order-service-w10:8001
        - name: CUSTOMER_API_BASE_URL
          value: http://customer-service-w10:8002
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-w10
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
