apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-w10
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service-container
        image: week10.azurecr.io/product_service:latest
        imagePullPolicy: Always
        imagePullSecrets:
      - name: acr-secret
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: product-service-w10
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
  type: LoadBalancer