name: Stage 3 - Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Production AKS cluster exists
        run: |
          az aks show --resource-group deakinuni --name week-10


      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group deakinuni \
            --name week-10 \
            --overwrite-existing

      - name: Deploy ConfigMaps and Secrets
        run: |
          kubectl apply -f k8s/configmaps.yaml
          kubectl apply -f k8s/secrets.yaml

      - name: Deploy backend services
        run: |
          kubectl apply -f k8s/product-service.yaml
          kubectl apply -f k8s/order-service.yaml
          kubectl apply -f k8s/customer-service.yaml

      - name: Check Pod Status
        run: |
          echo "Checking pod status..."
          kubectl get pods -o wide

      - name: Acceptance Test
        run: |
          kubectl get svc
          echo "Optionally curl exposed endpoints here"
