name: Stage 3 - Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    env:
      RESOURCE_GROUP: deakinuni
      CLUSTER_NAME: week-10

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify AKS cluster
        run: |
          az aks show --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --overwrite-existing

      - name: Deploy ConfigMaps and Secrets
        run: |
          kubectl apply -f k8s/configmaps.yaml
          kubectl apply -f k8s/secrets.yaml

      - name: Deploy backend services
        run: |
          kubectl apply -f k8s/product-service.yaml
          kubectl apply -f k8s/order-service.yaml
          kubectl apply -f k8s/customer-service.yaml

      - name: Check pod status
        run: kubectl get pods -o wide

      - name: Acceptance test
        run: kubectl get svc
